# Outcome from:
# kubectl create svc clusterip redis-svc --tcp=6379:6379 --namespace=database --dry-run=client -o yaml > vote-redis-svc.yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: redis-svc
  name: redis-svc
  namespace: database
spec:
  ports:
  - name: 6379-6379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis #Manually changed.
    #app: redis-svc #Auto delivered.
  type: ClusterIP
status:
  loadBalancer: {}
