apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"proxy"},"name":"proxy","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"proxy"}},"strategy":{},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"proxy"}},"spec":{"containers":[{"image":"nginx:1.17.0-alpine","name":"nginx","resources":{}}]}}},"status":{}}
  creationTimestamp: "2021-12-21T11:47:08Z"
  generation: 1
  labels:
    app: proxy
  name: proxy
  namespace: default
  resourceVersion: "14160"
  uid: 05650306-0f5b-4808-9733-6e4dc0edc056
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: proxy
    spec:
      containers:
      - image: nginx:1.17.0-alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-12-21T11:47:15Z"
    lastUpdateTime: "2021-12-21T11:47:15Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-12-21T11:47:08Z"
    lastUpdateTime: "2021-12-21T11:47:15Z"
    message: ReplicaSet "proxy-75cf797b87" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
