# Prepare YAML file for future usage by using --dry-run=client
# Outcome of command:
# kubectl create deployment proxy --image=nginx:1.17.0-alpine --dry-run=client -o yaml > proxy_deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: proxy
  name: proxy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: proxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: proxy
    spec:
      containers:
      - image: nginx:1.17.0-alpine
        name: nginx
        resources: {}
status: {}
