# Template for POD from k8s2 exercise.
# K8S always terminate the container due to too high usage of memory, which do not follow the limits.
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: stress-pod
  name: stress-pod
spec:
  containers:
  - name: stress-pod
    args:
      - --vm
      - "1"
      - --vm-bytes
      - 100M #memory is bigger than the limits from line 25.
      - --vm-hang
      - "1"
    command:
    - stress
    image: polinux/stress
    resources:
      limits:
        memory: "64Mi" 
        cpu: "100m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
